# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
            #- Before=2024-10-02T15:30:30+02:00[Europe/Paris]
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/api/products/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/orders/**
  config:
    import: optional:configserver:http://localhost:9999
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: DEBUG