# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: inventory-service
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9999
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventory-db
    username: inventory-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082

flyway:
  locations: db/migration

management:
  endpoint:
    web:
      exposure:
        include: "*"