# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: inventory-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventory-db

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082