# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9999
  h2:
      console:
        enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
    username: customer-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

flyway:
  locations: db/migration

management:
  endpoint:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: DEBUG