spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 8085

