spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ImproveMySkills/config-repo
          uri: file:///C:/javafx11/Source/config-cloud
          refresh-rate: 5
    refresh:
      enabled: true

server:
  port: 9999

management:
  endpoint:
    web:
      exposure:
        include: "*"